// examples/kitchen-sink/src/components/App.vue
<template>
    <h3>Shared</h3>
    <pre v-html="JSON.stringify(state, null, 2)" />
    
    <button @click="add">+</button>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { useStore } from '@exo-store/vue';
import MyStore from '../store';

export default defineComponent({
    setup() {
        const [state, store] = useStore(MyStore);
        const add = () => store.vue++;

        return {
            state,
            add
        }
    }
})
</script>

// examples/kitchen-sink/src/components/App.preact.tsx
import { FunctionalComponent, h } from 'preact';
import { useStore } from '@exo-store/preact';
import MyStore from '../store';

const App: FunctionalComponent = () => {
  const [state, store] = useStore(MyStore, (v) => v.preact);
  const add = () => store.preact++;

  return (
    <div>
      <h3>Hello from Preact!</h3>
      <pre>{JSON.stringify(state, null, 2)}</pre>

      <button onClick={add}>+</button>
    </div>
  );
};

export default App;
